version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Porta para comunicação entre serviços
      - "15672:15672"     # Painel do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - agenda-network

  agendaapi:
    build:
      context: .  # Caminho onde está o Dockerfile da API (dentro de /backend)
      dockerfile: AgendaApp.API/Dockerfile
    container_name: agenda-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMq__Host: rabbitmq
      ConnectionStrings__AgendaAppConnection: "Data Source=/app/Data/AgendaApp.db"
    volumes:
      - ./Data:/app/Data
    depends_on:
      - rabbitmq
    networks:
      - agenda-network

  frontend:
    build:
      context: ../frontend/agenda-app
      dockerfile: Dockerfile
    container_name: agenda-frontend
    ports:
      - "8081:80"
    depends_on:
      - agendaapi
    networks:
      - agenda-network

networks:
  agenda-network:
    driver: bridge